// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Producto struct {
	ID          int32          `json:"id"`
	Nombre      string         `json:"nombre"`
	Descripcion sql.NullString `json:"descripcion"`
	Categoria   sql.NullString `json:"categoria"`
	Color       sql.NullString `json:"color"`
	Precio      sql.NullInt32  `json:"precio"`
}

type Usuario struct {
	ID       int32  `json:"id"`
	Nombre   string `json:"nombre"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
