// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: producto.sql

package db

import (
	"context"
)

const createProducto = `-- name: CreateProducto :one
INSERT INTO producto (nombre, descripcion, categoria, color, precio)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, nombre, descripcion, categoria, color, precio
`

type CreateProductoParams struct {
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
	Categoria   string `json:"categoria"`
	Color       string `json:"color"`
	Precio      int32  `json:"precio"`
}

func (q *Queries) CreateProducto(ctx context.Context, arg CreateProductoParams) (Producto, error) {
	row := q.db.QueryRowContext(ctx, createProducto,
		arg.Nombre,
		arg.Descripcion,
		arg.Categoria,
		arg.Color,
		arg.Precio,
	)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Categoria,
		&i.Color,
		&i.Precio,
	)
	return i, err
}

const deleteProducto = `-- name: DeleteProducto :exec
DELETE FROM producto
WHERE id = $1
`

func (q *Queries) DeleteProducto(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteProducto, id)
	return err
}

const getAllProductos = `-- name: GetAllProductos :many
SELECT nombre, descripcion, categoria, color, precio
FROM producto
`

type GetAllProductosRow struct {
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
	Categoria   string `json:"categoria"`
	Color       string `json:"color"`
	Precio      int32  `json:"precio"`
}

func (q *Queries) GetAllProductos(ctx context.Context) ([]GetAllProductosRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductosRow
	for rows.Next() {
		var i GetAllProductosRow
		if err := rows.Scan(
			&i.Nombre,
			&i.Descripcion,
			&i.Categoria,
			&i.Color,
			&i.Precio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProducto = `-- name: GetProducto :one
SELECT nombre, descripcion, categoria, color, precio
FROM producto
WHERE id = $1
`

type GetProductoRow struct {
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
	Categoria   string `json:"categoria"`
	Color       string `json:"color"`
	Precio      int32  `json:"precio"`
}

func (q *Queries) GetProducto(ctx context.Context, id int32) (GetProductoRow, error) {
	row := q.db.QueryRowContext(ctx, getProducto, id)
	var i GetProductoRow
	err := row.Scan(
		&i.Nombre,
		&i.Descripcion,
		&i.Categoria,
		&i.Color,
		&i.Precio,
	)
	return i, err
}

const updateProducto = `-- name: UpdateProducto :one
UPDATE producto
SET nombre = $2, descripcion = $3, categoria = $4, color = $5, precio = $6
WHERE id = $1
RETURNING nombre, descripcion, categoria, color, precio
`

type UpdateProductoParams struct {
	ID          int32  `json:"id"`
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
	Categoria   string `json:"categoria"`
	Color       string `json:"color"`
	Precio      int32  `json:"precio"`
}

type UpdateProductoRow struct {
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
	Categoria   string `json:"categoria"`
	Color       string `json:"color"`
	Precio      int32  `json:"precio"`
}

func (q *Queries) UpdateProducto(ctx context.Context, arg UpdateProductoParams) (UpdateProductoRow, error) {
	row := q.db.QueryRowContext(ctx, updateProducto,
		arg.ID,
		arg.Nombre,
		arg.Descripcion,
		arg.Categoria,
		arg.Color,
		arg.Precio,
	)
	var i UpdateProductoRow
	err := row.Scan(
		&i.Nombre,
		&i.Descripcion,
		&i.Categoria,
		&i.Color,
		&i.Precio,
	)
	return i, err
}
