// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
)

const createUsuario = `-- name: CreateUsuario :one
INSERT INTO usuario (nombre, email, password)
VALUES ($1, $2, $3)
RETURNING id, nombre, email
`

type CreateUsuarioParams struct {
	Nombre   string `json:"nombre"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateUsuarioRow struct {
	ID     int32  `json:"id"`
	Nombre string `json:"nombre"`
	Email  string `json:"email"`
}

func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (CreateUsuarioRow, error) {
	row := q.db.QueryRowContext(ctx, createUsuario, arg.Nombre, arg.Email, arg.Password)
	var i CreateUsuarioRow
	err := row.Scan(&i.ID, &i.Nombre, &i.Email)
	return i, err
}

const deleteUsuario = `-- name: DeleteUsuario :exec
DELETE FROM usuario
WHERE id = $1
`

func (q *Queries) DeleteUsuario(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUsuario, id)
	return err
}

const getAllUsuarios = `-- name: GetAllUsuarios :many
SELECT id, nombre, email
FROM usuario
`

type GetAllUsuariosRow struct {
	ID     int32  `json:"id"`
	Nombre string `json:"nombre"`
	Email  string `json:"email"`
}

func (q *Queries) GetAllUsuarios(ctx context.Context) ([]GetAllUsuariosRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsuariosRow
	for rows.Next() {
		var i GetAllUsuariosRow
		if err := rows.Scan(&i.ID, &i.Nombre, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsuario = `-- name: GetUsuario :one
SELECT id, nombre, email
FROM usuario
WHERE id = $1
`

type GetUsuarioRow struct {
	ID     int32  `json:"id"`
	Nombre string `json:"nombre"`
	Email  string `json:"email"`
}

func (q *Queries) GetUsuario(ctx context.Context, id int32) (GetUsuarioRow, error) {
	row := q.db.QueryRowContext(ctx, getUsuario, id)
	var i GetUsuarioRow
	err := row.Scan(&i.ID, &i.Nombre, &i.Email)
	return i, err
}

const updateUsuario = `-- name: UpdateUsuario :one
UPDATE usuario
SET nombre = $2, email = $3, password = $4
WHERE id = $1
RETURNING nombre, email, password
`

type UpdateUsuarioParams struct {
	ID       int32  `json:"id"`
	Nombre   string `json:"nombre"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateUsuarioRow struct {
	Nombre   string `json:"nombre"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) (UpdateUsuarioRow, error) {
	row := q.db.QueryRowContext(ctx, updateUsuario,
		arg.ID,
		arg.Nombre,
		arg.Email,
		arg.Password,
	)
	var i UpdateUsuarioRow
	err := row.Scan(&i.Nombre, &i.Email, &i.Password)
	return i, err
}
